[2023-10-30T06:03:30.736+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-27T08:40:00+00:00 [queued]>
[2023-10-30T06:03:30.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-27T08:40:00+00:00 [queued]>
[2023-10-30T06:03:30.827+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 101
[2023-10-30T06:03:31.530+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_opensky_data> on 2023-10-27 08:40:00+00:00
[2023-10-30T06:03:31.579+0000] {standard_task_runner.py:57} INFO - Started process 110644 to run task
[2023-10-30T06:03:31.612+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'opensky_data_processing', 'fetch_opensky_data', 'scheduled__2023-10-27T08:40:00+00:00', '--job-id', '1060', '--raw', '--subdir', 'DAGS_FOLDER/DataFetcher.py', '--cfg-path', '/tmp/tmp4f1ivixs']
[2023-10-30T06:03:31.658+0000] {standard_task_runner.py:85} INFO - Job 1060: Subtask fetch_opensky_data
[2023-10-30T06:03:32.302+0000] {task_command.py:416} INFO - Running <TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-27T08:40:00+00:00 [running]> on host ip-172-31-33-29.ec2.internal
[2023-10-30T06:03:33.413+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adayani' AIRFLOW_CTX_DAG_ID='opensky_data_processing' AIRFLOW_CTX_TASK_ID='fetch_opensky_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-27T08:40:00+00:00'
[2023-10-30T06:03:42.288+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-30T06:03:42.346+0000] {process_utils.py:131} INFO - Sending 15 to group 110644. PIDs of all processes in the group: [110644]
[2023-10-30T06:03:42.346+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 110644
[2023-10-30T06:03:42.347+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-30T06:03:42.348+0000] {logging_mixin.py:151} INFO - Error: Task received SIGTERM signal
[2023-10-30T06:03:42.350+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-30T06:03:42.452+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=opensky_data_processing, task_id=fetch_opensky_data, execution_date=20231027T084000, start_date=20231030T060330, end_date=20231030T060342
[2023-10-30T06:03:43.018+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=110644, status='terminated', exitcode=0, started='06:03:31') (110644) terminated with exit code 0
