[2023-10-30T06:28:30.954+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-29T08:40:00+00:00 [queued]>
[2023-10-30T06:28:31.010+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-29T08:40:00+00:00 [queued]>
[2023-10-30T06:28:31.011+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 101
[2023-10-30T06:28:31.096+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_opensky_data> on 2023-10-29 08:40:00+00:00
[2023-10-30T06:28:31.141+0000] {standard_task_runner.py:57} INFO - Started process 142193 to run task
[2023-10-30T06:28:31.161+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'opensky_data_processing', 'fetch_opensky_data', 'scheduled__2023-10-29T08:40:00+00:00', '--job-id', '1656', '--raw', '--subdir', 'DAGS_FOLDER/DataFetcher.py', '--cfg-path', '/tmp/tmprl4lq87f']
[2023-10-30T06:28:31.207+0000] {standard_task_runner.py:85} INFO - Job 1656: Subtask fetch_opensky_data
[2023-10-30T06:28:31.597+0000] {task_command.py:416} INFO - Running <TaskInstance: opensky_data_processing.fetch_opensky_data scheduled__2023-10-29T08:40:00+00:00 [running]> on host ip-172-31-33-29.ec2.internal
[2023-10-30T06:28:32.159+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adayani' AIRFLOW_CTX_DAG_ID='opensky_data_processing' AIRFLOW_CTX_TASK_ID='fetch_opensky_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-29T08:40:00+00:00'
[2023-10-30T06:28:46.589+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-10-30T06:28:46.597+0000] {process_utils.py:131} INFO - Sending 15 to group 142193. PIDs of all processes in the group: [142193]
[2023-10-30T06:28:46.597+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 142193
[2023-10-30T06:28:46.597+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-30T06:28:46.598+0000] {logging_mixin.py:151} INFO - Error: Task received SIGTERM signal
[2023-10-30T06:28:46.600+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-30T06:28:46.635+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=opensky_data_processing, task_id=fetch_opensky_data, execution_date=20231029T084000, start_date=20231030T062830, end_date=20231030T062846
[2023-10-30T06:28:46.661+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=142193, status='terminated', exitcode=0, started='06:28:30') (142193) terminated with exit code 0
